export const CHECK_BOOKING_SUCCESS = 'CHECK_BOOKING_SUCCESS';
export const CHECK_BOOKING_FAILED = 'CHECK_BOOKING_FAILED';
export const CHECK_BOOKING_REQUEST = 'CHECK_BOOKING_REQUEST';
export const CHECK_BOOKING_RESET = 'CHECK_BOOKING_RESET';

export const BOOKED_DATES_SUCCESS = 'BOOKED_DATES_SUCCESS';
export const BOOKED_DATES_FAILED = 'BOOKED_DATES_FAILED';

export const MY_BOOKINGS_SUCCESS = 'MY_BOOKINGS_SUCCESS';
export const MY_BOOKINGS_FAILED = 'MY_BOOKINGS_FAILED';

export const BOOKING_DETAILS_SUCCESS = 'BOOKING_DETAILS_SUCCESS';
export const BOOKING_DETAILS_FAILED = 'BOOKING_DETAILS_FAILED';

export const ADMIN_BOOKINGS_SUCCESS = 'ADMIN_BOOKINGS_SUCCESS';
export const ADMIN_BOOKINGS_FAILED = 'ADMIN_BOOKINGS_FAILED';
export const ADMIN_BOOKINGS_REQUEST = 'ADMIN_BOOKINGS_REQUEST';

export const DELETE_BOOKING_SUCCESS = 'DELETE_BOOKING_SUCCESS';
export const DELETE_BOOKING_FAILED = 'DELETE_BOOKING_FAILED';
export const DELETE_BOOKING_REQUEST = 'DELETE_BOOKING_REQUEST';
export const DELETE_BOOKING_RESET = 'DELETE_BOOKING_RESET';

export const CLEAR_ERROR = 'CLEAR_ERROR';
