export const ALL_ROOM_SUCCESS = 'ALL_ROOM_SUCCESS';
export const ALL_ROOM_FAILED = 'ALL_ROOM_FAILED';

export const ROOM_DETAILS_SUCCESS = 'ROOM_DETAILS_SUCCESS';
export const ROOM_DETAILS_FAILED = 'ROOM_DETAILS_FAILED';

export const CLEAR_ERROR = 'CLEAR_ERROR';
