export const ALL_ROOM_SUCCESS = 'ALL_ROOM_SUCCESS';
export const ALL_ROOM_FAILED = 'ALL_ROOM_FAILED';

export const ROOM_DETAILS_SUCCESS = 'ROOM_DETAILS_SUCCESS';
export const ROOM_DETAILS_FAILED = 'ROOM_DETAILS_FAILED';

export const NEW_REVIEW_SUCCESS = 'NEW_REVIEW_SUCCESS';
export const NEW_REVIEW_FAILED = 'NEW_REVIEW_FAILED';
export const NEW_REVIEW_REQUEST = 'NEW_REVIEW_REQUEST';
export const NEW_REVIEW_RESET = 'NEW_REVIEW_RESET';

export const REVIEW_AVAILABILITY_SUCCESS = 'REVIEW_AVAILABILITY_SUCCESS';
export const REVIEW_AVAILABILITY_FAILED = 'REVIEW_AVAILABILITY_FAILED';
export const REVIEW_AVAILABILITY_REQUEST = 'REVIEW_AVAILABILITY_REQUEST';

export const ADMIN_ROOMS_SUCCESS = 'ADMIN_ROOMS_SUCCESS';
export const ADMIN_ROOMS_FAILED = 'ADMIN_ROOMS_FAILED';
export const ADMIN_ROOMS_REQUEST = 'ADMIN_ROOMS_REQUEST';

export const NEW_ROOM_SUCCESS = 'NEW_ROOM_SUCCESS';
export const NEW_ROOM_FAILED = 'NEW_ROOM_FAILED';
export const NEW_ROOM_REQUEST = 'NEW_ROOM_REQUEST';
export const NEW_ROOM_RESET = 'NEW_ROOM_RESET';

export const UPDATE_ROOM_SUCCESS = 'UPDATE_ROOM_SUCCESS';
export const UPDATE_ROOM_FAILED = 'UPDATE_ROOM_FAILED';
export const UPDATE_ROOM_REQUEST = 'UPDATE_ROOM_REQUEST';
export const UPDATE_ROOM_RESET = 'UPDATE_ROOM_RESET';

export const DELETE_ROOM_SUCCESS = 'DELETE_ROOM_SUCCESS';
export const DELETE_ROOM_FAILED = 'DELETE_ROOM_FAILED';
export const DELETE_ROOM_REQUEST = 'DELETE_ROOM_REQUEST';
export const DELETE_ROOM_RESET = 'DELETE_ROOM_RESET';

export const CLEAR_ERROR = 'CLEAR_ERROR';
